// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuceyoeyarjbszayhujh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1Y2V5b2V5YXJqYnN6YXlodWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDY5NDcsImV4cCI6MjA1ODk4Mjk0N30.0UppSm9FOUdQYX05svIPbImmbC2BmaX5IEcjA1ZEZMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);